name = "halve-z"
description = "Retro two-column theme"
license = "MIT"
homepage = "https://github.com/charlesrocket/halvez"
min_version = "0.18.0"
demo = "https://halve-z.netlify.app/"

[extra]
locale = "en_US"
logo = "fireball.gif"
manifest = ""
read_time = false
toc = true
csp = false

[extra.home]
title = "Halve-Z"
subtitle = "Zola theme"
glitch = false
logo = { enabled = true, height = "100", width = "100" }

[extra.images]
home = ""
post_list = ""
default_post = ""
categories = []

[extra.menu]
posts = false
links = [
    #{ name = "Code", url = "@/pages/projects.md" },
]

[extra.footer]
enabled = true
copyright = true
stack = true

[extra.social]
#email = ""
#mastodon = ""
#twitter = ""
#facebook = ""
#github = ""
#hackthebox = ""
#stackoverflow = ""
#linkedin = ""
#instagram = ""
#lastfm = ""
#reddit = ""
#twitch = ""
#flickr = ""
#keybase = ""
#xmpp = ""
#hackernews = ""

[extra.comments]
system = ""

[extra.comments.cactus]
site = ""
page_size = 10
guest_posting = true
update_interval = 0

[extra.comments.giscus]
repo = ""
repo_id = ""
category = ""
category_id = ""
mapping = ""
strict = "1"
reactions = "0"
lang = "en"

[author]
name = "-k"
homepage = "https://failsafe.monster/"

[original]
author =  "Taylan TatlÄ±"
homepage = "https://tatli.me/"
repo = "https://github.com/TaylanTatli/Halve"
